branch-defaults:
  default:
    environment: Udagramapi-env-1
environment-defaults:
  Udagramapi-env-1:
    branch: null
    repository: null
global:
  application_name: udagram-api
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
