version: 2.1
orbs:
  # orbs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  # different jobs are called later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # set up aws-cli
      - aws-cli/setup
      # set up eb-cli
      - aws-elastic-beanstalk/setup
      # install dependencies in both apps
      - run:
          name: install frontend deps
          command: npm run frontend:install
      - run:
          name: install backend deps
          command: npm run backend:install 
      # build front and the back end
      - run:
          name: build frontend
          command: npm run frontend:build
      - run:
          name: builde backend
          command: npm run backend:build
      # deploy the backend to eb
      - run:
          name: deploy backend to ebs
          command: npm run backend:deploy
      # # deploy the ui to s3
      - run:
          name: deploy ui to s3
          command: npm run frontend:deploy
      